
version: 2

models:
    - name: browsing_flattened
      description: "Browsing data with JSON column flattened."
      columns:
          - name: session_id_hash
            description: "session id"
            tests:
                - not_null
          - name: organization_id
            description: "organization id"
            tests:
                - not_null
          - name: event_type
            description: "event_type"
          - name: product_sku_hash
            description: "product_sku_hash"
          - name: hashed_url
            description: "hashed url"

    - name: search_flattened
      description: "Search events with JSON column flattened."
      columns:
        - name: server_timestamp_epoch_ms
          description: "time of the search"
          tests:
            - not_null
        - name: organization_id
          description: "organization id"
          tests:
            - not_null
        - name: query_string
          description: "query string"
        - name: product_sku_hash
          description: "product_sku_hash"
        - name: rank
          description: "rank"
        - name: query_vector
          description: "query_vector"

    - name: content_flattened
      description: "Raw content with JSON column flattened."
      columns:
        - name: product_sku_hash
          description: "product_sku_hash"
          tests:
            - not_null
        - name: ingestion_timestamp_epoch_ms
          description: "time stamp"
          tests:
            - not_null
        - name: organization_id
          description: "organization id"
          tests:
            - not_null
        - name: item_vector
          description: "item vector"
        - name: image_vector
          description: "image vector"
        - name: price_bucket
          description: "price bucket"