service: metaflow-intent-remote-endpoint

provider:
  name: aws
  runtime: python3.8
  stage: ${env:STAGE, 'dev'}
  region: ${env:AWS_DEFAULT_REGION, 'us-west-2'}
  lambdaHashingVersion: 20201221

package:
  individually: true
  patterns:
    - "!*/**"
    - "!*"

functions:
  predict:
    handler: handler.predict
    environment:
      SAGEMAKER_ENDPOINT_NAME: ${env:SAGEMAKER_ENDPOINT_NAME}
    events:
      - http:
          path: predict
          method: get
    package:
      patterns:
        - handler.py
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sagemaker:InvokeEndpoint
        Resource:
          Fn::Join:
            - ':'
            - - arn
              - aws
              - sagemaker
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - endpoint/${env:SAGEMAKER_ENDPOINT_NAME}

plugins:
  - serverless-iam-roles-per-function
