frameworkVersion: ">=1.24.1"

service: metaflow-intent-remote-endpoint

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    # default: serverless project root
    path: ../.env

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-west-2


functions:
  prediction_api:
    environment:
      SAGEMAKER_ENDPOINT_NAME: ${env:SAGEMAKER_ENDPOINT_NAME}
      SAGE_USER: ${env:SAGE_USER}
      SAGE_SECRET: ${env:SAGE_SECRET}
      SAGE_REGION: ${env:SAGE_REGION}

    handler: handler.predict
    events:
      - http:
          path: predict
          method: get
